baseURL: https://abfoundation.com
languageCode: zh-cn
title: AB基金会
enableEmoji: true
enableGitInfo: true
defaultContentLanguage: zh-cn
languages:
  zh-CN:
    languageCode: zh-cn
    languageName: 简体中文
    contentDir: content
    weight: 1
  en:
    languageCode: en
    languageName: English
    contentDir: content
    weight: 2